In [1]:
#author: steeve laquitaine
#setup
from assets.gen_motion import *
import numpy as np
%load_ext autoreload
%autoreload 2s

In [ ]:
#gen_dataset(size, N, types, velocity, theta, coherence, dots, direction)
X_train,Y_train,X_test,Y_test = gen_dataset((16,32,32),20,['translate','expandContract','opticflow','rotation'],[0],[0],[0],[150],[-1,1])
print X_train.shape
print Y_train.shape
print X_test.shape
print Y_test.shape

In [2]:
X_train,Y_train,X_test,Y_test = gen_dataset((16,32,32),20,'square', (5,5,0), 0, 1, ['translate'],[0],[0],[0],[150],[-1,1])
print X_train.shape
print Y_train.shape
print X_test.shape
print Y_test.shape

(36, 1, 16, 32, 32)
(36, 6)
(4, 1, 16, 32, 32)
(4, 6)


In [3]:
print X_train[0,0,0,:,:]

[[   0.    0.    0. ...,    0.    0.    0.]
 [ 255.    0.  255. ...,    0.    0.    0.]
 [ 255.    0.    0. ...,    0.    0.  255.]
 ..., 
 [   0.    0.    0. ...,    0.    0.    0.]
 [   0.    0.    0. ...,    0.    0.    0.]
 [   0.    0.    0. ...,    0.    0.    0.]]


In [4]:
print Y_train

[[ 1.  1.  1.  1.  1.  0.]
 [ 1.  1.  1.  1.  1.  0.]
 [ 1.  1.  1.  1.  1.  0.]
 [ 1.  1.  1.  1.  1.  0.]
 [ 1.  1.  1.  1.  1.  0.]
 [ 1.  1.  1.  1.  1.  0.]
 [ 1.  1.  1.  1.  1.  0.]
 [ 1.  1.  1.  1.  1.  0.]
 [ 1.  1.  1.  1.  1.  0.]
 [ 1.  1.  1.  1.  1.  0.]
 [ 1.  1.  1.  1.  1.  0.]
 [ 1.  1.  1.  1.  1.  0.]
 [ 1.  1.  1.  1.  1.  0.]
 [ 1.  1.  1.  1.  1.  0.]
 [ 1.  1.  1.  1.  1.  0.]
 [ 1.  1.  1.  1.  1.  0.]
 [ 1.  1.  1.  1.  1.  0.]
 [ 1.  1.  1.  1.  1.  0.]
 [ 1.  1.  1.  1.  1.  0.]
 [ 1.  1.  1.  1.  1.  0.]
 [ 1.  1.  1.  1.  1.  0.]
 [ 1.  1.  1.  1.  1.  0.]
 [ 1.  1.  1.  1.  1.  0.]
 [ 1.  1.  1.  1.  1.  0.]
 [ 1.  1.  1.  1.  1.  0.]
 [ 1.  1.  1.  1.  1.  0.]
 [ 1.  1.  1.  1.  1.  0.]
 [ 1.  1.  1.  1.  1.  0.]
 [ 1.  1.  1.  1.  1.  0.]
 [ 1.  1.  1.  1.  1.  0.]
 [ 1.  1.  1.  1.  1.  0.]
 [ 1.  1.  1.  1.  1.  0.]
 [ 1.  1.  1.  1.  1.  0.]
 [ 1.  1.  1.  1.  1.  0.]
 [ 1.  1.  1.  1.  1.  0.]
 [ 1.  1.  1.  1.  1.  0.]]
