### Setup

In [105]:
#author: steeve laquitaine
#setup
from assets.gen_motion import *
import numpy as np
from assets.vis_utils import visualize_matrix2
%load_ext autoreload
%autoreload 2
%matplotlib nbagg

ImportError: cannot import name visualize_matrix2

### Generate example downward motion

In [103]:
#gen_dataset(size, N, types, velocity, theta, coherence, dots, direction)
# X_train,Y_train,X_test,Y_test = gen_dataset((16,32,32),20,['translate','expandContract','opticflow','rotation'],[0],[0],[0],[150],[-1,1])
X_train, Y_train,X_val,Y_val, X_test, Y_test = gen_dataset((16,32,32),1,None,['translate'],[1],[0],[1],[150],[1],vt_prop=0.1,dot_radius=1,contrast=1,Snoise=10,retina=1)
print X_train.shape
print Y_train.shape
print X_test.shape
print Y_test.shape
print X_train_LGN.shape
print X_val_LGN.shape
print X_test_LGN.shape

(1, 1, 16, 32, 32)
(1, 6)
(0, 1, 16, 32, 32)
(0, 6)
(1, 1, 16, 32, 32)
(0, 1, 16, 32, 32)
(0, 1, 16, 32, 32)


### Visualize one train video

In [104]:
#get 1st example raw motion
c = X_train[0,:,:,:,:][0]

#visualize
visualize_matrix2(c)

NameError: name 'visualize_matrix2' is not defined

In [2]:
X_train,Y_train,X_test,Y_test = gen_dataset((16,32,32),20,'square', (5,5,0), 0, 1, ['translate'],[0],[0],[0],[150],[-1,1])
print X_train.shape
print Y_train.shape
print X_test.shape
print Y_test.shape

(36, 1, 16, 32, 32)
(36, 6)
(4, 1, 16, 32, 32)
(4, 6)


In [3]:
print X_train[0,0,0,:,:]

[[   0.    0.    0. ...,    0.    0.    0.]
 [ 255.    0.  255. ...,    0.    0.    0.]
 [ 255.    0.    0. ...,    0.    0.  255.]
 ..., 
 [   0.    0.    0. ...,    0.    0.    0.]
 [   0.    0.    0. ...,    0.    0.    0.]
 [   0.    0.    0. ...,    0.    0.    0.]]


In [4]:
print Y_train

[[ 1.  1.  1.  1.  1.  0.]
 [ 1.  1.  1.  1.  1.  0.]
 [ 1.  1.  1.  1.  1.  0.]
 [ 1.  1.  1.  1.  1.  0.]
 [ 1.  1.  1.  1.  1.  0.]
 [ 1.  1.  1.  1.  1.  0.]
 [ 1.  1.  1.  1.  1.  0.]
 [ 1.  1.  1.  1.  1.  0.]
 [ 1.  1.  1.  1.  1.  0.]
 [ 1.  1.  1.  1.  1.  0.]
 [ 1.  1.  1.  1.  1.  0.]
 [ 1.  1.  1.  1.  1.  0.]
 [ 1.  1.  1.  1.  1.  0.]
 [ 1.  1.  1.  1.  1.  0.]
 [ 1.  1.  1.  1.  1.  0.]
 [ 1.  1.  1.  1.  1.  0.]
 [ 1.  1.  1.  1.  1.  0.]
 [ 1.  1.  1.  1.  1.  0.]
 [ 1.  1.  1.  1.  1.  0.]
 [ 1.  1.  1.  1.  1.  0.]
 [ 1.  1.  1.  1.  1.  0.]
 [ 1.  1.  1.  1.  1.  0.]
 [ 1.  1.  1.  1.  1.  0.]
 [ 1.  1.  1.  1.  1.  0.]
 [ 1.  1.  1.  1.  1.  0.]
 [ 1.  1.  1.  1.  1.  0.]
 [ 1.  1.  1.  1.  1.  0.]
 [ 1.  1.  1.  1.  1.  0.]
 [ 1.  1.  1.  1.  1.  0.]
 [ 1.  1.  1.  1.  1.  0.]
 [ 1.  1.  1.  1.  1.  0.]
 [ 1.  1.  1.  1.  1.  0.]
 [ 1.  1.  1.  1.  1.  0.]
 [ 1.  1.  1.  1.  1.  0.]
 [ 1.  1.  1.  1.  1.  0.]
 [ 1.  1.  1.  1.  1.  0.]]
